# Generated by Django 5.1.1 on 2024-09-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id_specialization', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id_health_professional', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_specialization', to='healthcareProfessional.specialization')),
            ],
        ),
    ]
