# Generated by Django 5.1.1 on 2024-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareProfessional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofessional',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
