# Generated by Django 5.1.1 on 2024-09-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareProfessional', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthProfessional',
        ),
    ]
