# Generated by Django 5.1.1 on 2024-09-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareProfessional', '0002_delete_healthprofessional'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcareProfessional.specialization')),
            ],
        ),
    ]
